name: main
on:
  push:
    branches: [main]
  schedule:
    - cron: "15 8 * * *"
  workflow_dispatch:

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - run: pdm install --frozen-lock
      - run: git config --global user.name 'Github Actions'
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: pdm run script.py
      - run: pdm run pre-commit run -a || echo 'returncode ignored'
      - run: |
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
          git push origin HEAD:refs/heads/main --tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
